# Generated by Django 4.1 on 2023-07-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customers",
            name="token",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
