# Generated by Django 4.1 on 2023-07-11 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_content", "0003_myowntoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customers",
            name="token",
        ),
    ]
