# Generated by Django 4.1 on 2023-07-15 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_content", "0006_roles_customers_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_image", models.ImageField(blank=True, null=True, upload_to="")),
                ("title", models.CharField(max_length=120)),
                ("main_images", models.FileField(blank=True, null=True, upload_to="")),
                ("main_text", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_content.customers",
                    ),
                ),
            ],
        ),
    ]
