# Generated by Django 4.1 on 2023-07-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_content", "0007_blogs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_content.customers",
            ),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="main_images",
            field=models.FileField(blank=True, null=True, upload_to="main/"),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="title_image",
            field=models.ImageField(blank=True, null=True, upload_to="title/"),
        ),
    ]
