# Generated by Django 4.1 on 2023-07-17 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_content", "0008_alter_blogs_author_alter_blogs_main_images_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogs",
            name="main_images",
        ),
        migrations.CreateModel(
            name="BlogImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_images",
                    models.ImageField(blank=True, null=True, upload_to="main/"),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_content.blogs",
                    ),
                ),
            ],
        ),
    ]
