# Generated by Django 4.1 on 2023-07-27 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_content", "0010_blogs_dislikes_blogs_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="create",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 7, 27, 14, 5, 40, 958456, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
