# Generated by Django 4.1 on 2023-07-28 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main_content", "0011_blogs_create"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogs",
            name="create",
        ),
        migrations.AddField(
            model_name="blogs",
            name="create_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogs",
            name="create_time",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
