# Generated by Django 4.1 on 2023-08-01 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_content", "0012_remove_blogs_create_blogs_create_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReactionsCustomers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("likes", models.BooleanField()),
                ("dislikes", models.BooleanField()),
                (
                    "blog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_content.blogs",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_content.customers",
                    ),
                ),
            ],
        ),
    ]
